### PR TITLE
Account Page Mockup + My Archives Page

### PR DESCRIPTION
**Pull request by danZzyy**
Header and Account page static content looks like this
image
Feedback is appreciated

### CODE REVIEW

**Comment by IsabellaS09** [comment]
Are you using the bootstrap styles?

**Comment by danZzyy** [comment]
Im using the stylesheet but I only imported it to  use the glyphicons. Im not using the grid or column system

**Comment by IsabellaS09** [comment]
The padding of the boxes looks a bit pushed together. I think you could use more bootstrap components like this http://bootsnipp.com/snippets/featured/simple-user-profile.

**Comment by danZzyy** [comment]
image

**Comment by IsabellaS09** [comment]
Lol My Archives Page. Awesome, I think this can be merged.

**Pull request merged**
