### PR TITLE
The Create Page (Is not even close to ready)

### PR DESCRIPTION
**Pull request by kdelancey**
Mess of CSS, JS, and HTML files. But check out the c00l n4vb4r guy$. Not all forms are fleshed out, and I hate the spacing of the margins as it stands. I want there to be a border around the carousel as well. In general, looks rough, but better than yesterday! :100: 

image

### CODE REVIEW

**Comment by danZzyy** [comment]
cool beans. good place to track progress. for this phase i dont think stylistic consistency is super important as long as we are working off of the same mockups

**Comment by kdelancey** [comment]
First part:
image

Second part:
image

It's very simple, and @ncbaihly  @IsabellaS09 @danZzyy I wonder how much I should tweak it to match the data we want to simulate in the Curation and My Event page.

**Comment by IsabellaS09** [comment]
Looks great! I think the only thing it needs is the place where you can add contributors.

**Comment by kdelancey** [comment]
First Carousel:
image

Second Carousel:
image



Third Carousel:
image

Modal:
image

After 'addition':
image

The carousel is kinda glitchy; the items within do not move seamlessly. Other than that, it looks nice! Lemme know your feedback.

**Comment by IsabellaS09** [comment]
Cool Cool, I think this can be merged.

**Comment by IsabellaS09** [comment]
I think the colors on the Add Contributor modal should be changed, but that can be taken care of after merge.

**Pull request merged**
